title: "Alhousseynou Agne"
logo: /images/profile.jpg
description: "Portfolio | Étudiant Ingénieur en Télécommunications & Réseaux | Technicien Support IT"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
